
// Generated by Cadence Genus(TM) Synthesis Solution 17.22-s017_1
// Generated on: Oct 23 2023 13:18:21 IST (Oct 23 2023 07:48:21 UTC)

// Verification Directory fv/counter 

module counter(clk, rst, out, SE, scan_in, scan_out);
  input clk, rst, SE, scan_in;
  output [3:0] out;
  output scan_out;
  wire clk, rst, SE, scan_in;
  wire [3:0] out;
  wire scan_out;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  assign scan_out = out[3];
  sdnrq4 \out_reg[3] (.CP (clk), .D (n_7), .SD (out[2]), .SC (SE), .Q
       (out[3]));
  sdnrq4 \out_reg[2] (.CP (clk), .D (n_6), .SD (out[1]), .SC (SE), .Q
       (out[2]));
  oan211d1 g97__8780(.A (n_1), .B (n_4), .C1 (n_5), .C2 (out[3]), .ZN
       (n_7));
  sdnrq4 \out_reg[1] (.CP (clk), .D (n_3), .SD (out[0]), .SC (SE), .Q
       (out[1]));
  ora211d1 g100__4296(.A (n_5), .B (rst), .C1 (n_2), .C2 (out[2]), .Z
       (n_6));
  sdnrq4 \out_reg[0] (.CP (clk), .D (n_0), .SD (scan_in), .SC (SE), .Q
       (out[0]));
  nd02d0 g99__3772(.A1 (n_5), .A2 (out[3]), .ZN (n_4));
  aoim211d1 g103__1474(.A (n_2), .B (n_1), .C1 (out[1]), .C2 (out[0]),
       .ZN (n_3));
  nd02d1 g102__4547(.A1 (n_2), .A2 (out[2]), .ZN (n_5));
  nr02d1 g105__9682(.A1 (n_1), .A2 (out[0]), .ZN (n_0));
  an02d1 g106__2683(.A1 (out[0]), .A2 (out[1]), .Z (n_2));
  inv0d0 g107(.I (rst), .ZN (n_1));
endmodule

