
// Generated by Cadence Genus(TM) Synthesis Solution 17.22-s017_1
// Generated on: Oct 11 2023 18:10:22 IST (Oct 11 2023 12:40:22 UTC)

// Verification Directory fv/counter 

module counter(clk, rst, out);
  input clk, rst;
  output [3:0] out;
  wire clk, rst;
  wire [3:0] out;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  dfnrq1 \out_reg[3] (.CP (clk), .D (n_7), .Q (out[3]));
  oan211d1 g97__8780(.A (n_1), .B (n_4), .C1 (n_5), .C2 (out[3]), .ZN
       (n_7));
  dfnrq1 \out_reg[2] (.CP (clk), .D (n_6), .Q (out[2]));
  ora211d1 g100__4296(.A (n_5), .B (rst), .C1 (n_2), .C2 (out[2]), .Z
       (n_6));
  dfnrq1 \out_reg[1] (.CP (clk), .D (n_3), .Q (out[1]));
  nd02d1 g99__3772(.A1 (n_5), .A2 (out[3]), .ZN (n_4));
  dfnrq1 \out_reg[0] (.CP (clk), .D (n_0), .Q (out[0]));
  aoim211d1 g103__1474(.A (n_2), .B (n_1), .C1 (out[0]), .C2 (out[1]),
       .ZN (n_3));
  nd02d1 g102__4547(.A1 (n_2), .A2 (out[2]), .ZN (n_5));
  nr02d1 g105__9682(.A1 (n_1), .A2 (out[0]), .ZN (n_0));
  an02d1 g106__2683(.A1 (out[1]), .A2 (out[0]), .Z (n_2));
  inv0d0 g107(.I (rst), .ZN (n_1));
endmodule

